name: asan

on:
  push:
    branches:
      - 'main'
      - 'dev**'

env:
  TARGET_ARCH: linux64
  GITHUB_TOKEN: ${{secrets.CI_TOKEN}}
  ASAN_OPTIONS: verbosity=1
  TSAN_OPTIONS: verbosity=1
  UBSAN_OPTIONS: print_stacktrace=1

jobs:
  sanitize:
    name: ${{matrix.sanitizer}}
    runs-on: self-hosted-ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        sanitizer: [ASAN, TSAN, UBSAN]

    steps:
    - name: Checkout VCML CCI
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{secrets.CI_TOKEN}}

    - name: Configure
      run: cmake -B BUILD -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.sanitizer}} -DVCML_CCI_TESTS=ON .

    - name: Build
      run: cmake --build BUILD

    - name: Test
      run: ctest --test-dir BUILD --output-on-failure

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: vcml-cci-build-logs-${{matrix.sanitizer}}
        path: |
            BUILD/.ninja_log
            BUILD/CMakeCache.txt
            BUILD/Testing/Temporary/LastTest.log
        include-hidden-files: true
        retention-days: 7

