name: cmake

on:
  push:
    branches:
      - 'main'
      - 'dev**'
  pull_request:
    branches:
      - 'main'

env:
  BUILD_TYPE: RELEASE
  GITHUB_TOKEN: ${{secrets.CI_TOKEN}}

jobs:
  cmake:
    name: cmake
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [self-hosted-ubuntu-22.04, self-hosted-ubuntu-20.04, self-hosted-rhel-8, self-hosted-ubuntu-22.04-arm64, self-hosted-windows-2022]

    steps:
    - name: Checkout Model
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{secrets.CI_TOKEN}}

    - name: Configure
      run: cmake -B BUILD -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTEMPLATE_MODEL_TESTS=ON .

    - name: Build
      run: cmake --build BUILD --config ${{env.BUILD_TYPE}} -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/BUILD
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

