name: coverage

on:
  push:
    branches:
      - 'main'
      - 'dev**'

env:
  BUILD_TYPE: DEBUG
  GITHUB_TOKEN: ${{secrets.CI_TOKEN}}

jobs:
  coverage:
    name: coverage
    runs-on: self-hosted-ubuntu-24.04

    steps:
    - name: Checkout VCML CCI
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{secrets.CI_TOKEN}}

    - name: Configure
      run: |
        cmake -B BUILD -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                                -DSYSTEMC_UNITY_BUILD=ON \
                                -DVCML_UNITY_BUILD=ON \
                                -DVCML_CCI_TESTS=ON \
                                -DVCML_CCI_COVERAGE=ON .

    - name: Build
      run: cmake --build BUILD

    - name: Test
      working-directory: BUILD
      run: ctest --output-on-failure

    - name: Generate Coverage Report
      run: |
        mkdir -p ${{github.event.repository.name}}-coverage-report
        gcovr --html-details -f 'include/*' -f 'src/*' \
              --output ${{github.event.repository.name}}-coverage-report/${{github.event.repository.name}}.html \
              --exclude-lines-by-pattern '\s*(VCML|MWR)_ERROR.*'

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        retention-days: 7
        name: ${{github.event.repository.name}}-coverage-report
        path: ${{github.event.repository.name}}-coverage-report/

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: ${{github.event.repository.name}}-logs-coverage
        path: |
            BUILD/.ninja_log
            BUILD/CMakeCache.txt
            BUILD/Testing/Temporary/LastTest.log
        include-hidden-files: true
        retention-days: 7

