name: nightly

on:
  schedule:
    - cron: '0 1 * * *'

env:
  BUILD_TYPE: RELEASE
  GITHUB_TOKEN: ${{secrets.CI_TOKEN}}

jobs:
  nightly:
    name: nightly
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [self-hosted-ubuntu-22.04, self-hosted-ubuntu-20.04, self-hosted-rhel-8, self-hosted-ubuntu-22.04-arm64, self-hosted-windows-2022]

    steps:
    - name: Checkout VCML CCI
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{secrets.CI_TOKEN}}

    - name: Configure
      if: runner.os != 'Windows'
      run: cmake -B BUILD -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DVCML_CCI_TESTS=ON .

    - name: Configure (Windows)
      if: runner.os == 'Windows'
      run: cmake -B BUILD -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DVCML_CCI_TESTS=ON .

    - name: Build
      if: runner.os != 'Windows'
      run: cmake --build BUILD

    - name: Build (Windows)
      if: runner.os == 'Windows'
      run: cmake --build BUILD --config ${{env.BUILD_TYPE}} -- /bl

    - name: Test
      run: ctest --test-dir BUILD -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: vcml-cci-build-logs-${{matrix.os}}
        path: |
            BUILD/.ninja_log
            BUILD/CMakeCache.txt
            BUILD/msbuild.binlog
            BUILD/Testing/Temporary/LastTest.log
        include-hidden-files: true
        retention-days: 7

